ramp:
  angle: 8
box:
  inX: 1740
  outX: 2050
  topSpeed: 4
bears:
  width: 12
  height: 24
  airFriction: 0.01
  staticFriction: 0.5
  friction: 0.000025
  mass: 0.5
  restitution: 0.4
  slop: 0.2
chutes:
  count: 9
  width: 60
  height: 200 # min on-screen height
  spacing: 170
